apiVersion: apps/v1
kind: Deployment
metadata:
  name: producao
  labels:
    app: producao
spec:
  template:
    metadata:
      name: producao
      labels:
        app: producao
    spec:
      serviceAccountName: producao-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: producao-secrets
        - name: producao-volume
          hostPath:
            path: /home/producao-volume
            type: DirectoryOrCreate
      containers:
        - name: auth
          image: vwnunes/tech-challenge-61-producao:latest
          ports:
            - containerPort: 8083
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: producao-secrets-aws
                  key: mongoURI
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: producao-secrets-aws
                  key: mongoDatabase
          volumeMounts:
            - name: producao-volume
              mountPath: /mnt/producao-volume
            - name: secrets-store-inline
              mountPath: "/mnt/producao-secrets"
              readOnly: true
  replicas: 2
  selector:
    matchLabels:
      app: producao
