apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: producao-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/tech-challenge-producao/dev/MONGODB_DATABASE"
        objectType: "ssmparameter"
        objectAlias: mongoDatabase
      - objectName: "/tech-challenge-producao/dev/MONGODB_URI"
        objectType: "ssmparameter"
        objectAlias: mongoURI
  secretObjects:
    - secretName: producao-secrets-aws
      type: Opaque
      data:
        - objectName: mongoDatabase
          key: mongoDatabase
        - objectName: mongoURI
          key: mongoURI